use crate::git::CommitInfo;
use std::io::IsTerminal;

pub struct AgentDetector {
    patterns: Vec<String>,
}

impl AgentDetector {
    pub fn new(patterns: Vec<String>) -> Self {
        AgentDetector { patterns }
    }

    pub fn detect_from_commit(&self, commit: &CommitInfo) -> Option<String> {
        let message_lower = commit.message.to_lowercase();

        for pattern in &self.patterns {
            let pattern_lower = pattern.to_lowercase();

            if message_lower.contains(&pattern_lower) {
                return Some(pattern.clone());
            }

            for co_author in &commit.co_authors {
                if co_author.to_lowercase().contains(&pattern_lower) {
                    return Some(pattern.clone());
                }
            }
        }

        None
    }

    pub fn detect_from_environment(&self) -> Option<String> {
        let checks: &[(&str, &str)] = &[
            ("CLAUDE_CODE", "Claude"),
            ("CURSOR_SESSION", "Cursor"),
            ("GITHUB_COPILOT", "Copilot"),
            ("WINDSURF_SESSION", "Windsurf"),
            ("DEVIN_SESSION", "Devin"),
        ];

        for (var, name) in checks {
            if std::env::var(var).is_ok() {
                return Some(name.to_string());
            }
        }

        None
    }

    pub fn detect_from_tty() -> bool {
        std::io::stdin().is_terminal()
    }

    pub fn tag_for_entry(&self, commit: Option<&CommitInfo>) -> Option<String> {
        if let Some(c) = commit {
            if let Some(agent) = self.detect_from_commit(c) {
                return Some(agent);
            }
        }

        if let Some(agent) = self.detect_from_environment() {
            return Some(agent);
        }

        if !Self::detect_from_tty() {
            return Some("unknown-agent".to_string());
        }

        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn default_detector() -> AgentDetector {
        AgentDetector::new(vec![
            "Claude".to_string(),
            "Copilot".to_string(),
            "Cursor".to_string(),
        ])
    }

    #[test]
    fn test_detect_from_commit_co_author() {
        let detector = default_detector();
        let commit = CommitInfo {
            hash: "abc123".to_string(),
            author: "Juste".to_string(),
            message: "Fix bug".to_string(),
            date: "2026-02-14T10:00:00+00:00".to_string(),
            co_authors: vec!["Claude <noreply@anthropic.com>".to_string()],
        };

        let result = detector.detect_from_commit(&commit);
        assert_eq!(result, Some("Claude".to_string()));
    }

    #[test]
    fn test_detect_from_commit_message() {
        let detector = default_detector();
        let commit = CommitInfo {
            hash: "def456".to_string(),
            author: "Dev".to_string(),
            message: "Generated by Copilot".to_string(),
            date: "2026-02-14T10:00:00+00:00".to_string(),
            co_authors: vec![],
        };

        let result = detector.detect_from_commit(&commit);
        assert_eq!(result, Some("Copilot".to_string()));
    }

    #[test]
    fn test_detect_from_commit_no_agent() {
        let detector = default_detector();
        let commit = CommitInfo {
            hash: "789abc".to_string(),
            author: "Human Developer".to_string(),
            message: "Manual refactor of login flow".to_string(),
            date: "2026-02-14T10:00:00+00:00".to_string(),
            co_authors: vec![],
        };

        let result = detector.detect_from_commit(&commit);
        assert_eq!(result, None);
    }

    #[test]
    fn test_new_with_custom_patterns() {
        let detector = AgentDetector::new(vec![
            "MyBot".to_string(),
            "CustomAgent".to_string(),
        ]);

        let commit = CommitInfo {
            hash: "111222".to_string(),
            author: "Dev".to_string(),
            message: "Changes from MyBot session".to_string(),
            date: "2026-02-14T10:00:00+00:00".to_string(),
            co_authors: vec![],
        };

        let result = detector.detect_from_commit(&commit);
        assert_eq!(result, Some("MyBot".to_string()));
    }
}
